require "test_helper"

# §C. Three call sites enqueued ContentPipelineJob and only one claimed atomically.
# ContentPipelineJob guards on `content_ready` but NOT `content_generating`, so enqueuing
# a step that is still in flight runs a second full pipeline and pays for a second
# lesson_content call (~3¢ measured). These tests pin the claim, the cap and idempotency.
class LearningRoutesEngine::ContentPrefetcherTest < ActiveSupport::TestCase
  # ActiveSupport::TestCase does not include the ActiveJob assertions by default here.
  include ActiveJob::TestHelper
  CP = LearningRoutesEngine::ContentPrefetcher
  PIPELINE = LearningRoutesEngine::ContentPipelineJob

  def setup
    @user = Core::User.create!(
      name: "Prefetch", email: "pf-#{SecureRandom.hex(4)}@example.com",
      password: "password123", password_confirmation: "password123",
      email_verified_at: Time.current
    )
    @profile = LearningRoutesEngine::LearningProfile.create!(user: @user, current_level: "beginner")
    @route = LearningRoutesEngine::LearningRoute.create!(
      learning_profile: @profile, topic: "T", locale: "en", status: :active
    )
    @steps = 6.times.map do |i|
      @route.route_steps.create!(
        title: "Step #{i}", position: i, status: i.zero? ? :available : :locked,
        content_type: "lesson", delivery_format: "text", level: 1, bloom_level: 1
      )
    end
  end

  def mark(step, **flags)
    step.update!(metadata: (step.metadata || {}).merge(flags.transform_keys(&:to_s)))
  end

  test "claims only steps that are neither ready nor already generating" do
    mark(@steps[0], content_ready: true)
    mark(@steps[1], content_generating: true)

    claimed = CP.claim(@steps.map(&:id), access_states: CP::PREVIEW_ONLY)

    assert_not_includes claimed, @steps[0].id, "a ready step must not be re-claimed"
    assert_not_includes claimed, @steps[1].id, "an in-flight step must not be re-claimed — this is the double-billing case"
    assert_includes claimed, @steps[2].id
  end

  test "claiming is atomic — a second claim of the same steps returns nothing" do
    first = CP.claim(@steps.map(&:id), access_states: CP::PREVIEW_ONLY)
    second = CP.claim(@steps.map(&:id), access_states: CP::PREVIEW_ONLY)

    assert first.any?
    assert_equal [], second, "the loser of the race must claim nothing"
  end

  test "the claim flips content_generating without destroying other metadata" do
    @steps[0].update!(metadata: { "parsed_sections" => [{ "type" => "concept" }], "keep" => "me" })

    CP.claim([@steps[0].id], access_states: CP::PREVIEW_ONLY)

    md = @steps[0].reload.metadata
    assert_equal true, md["content_generating"]
    assert_equal "me", md["keep"], "jsonb_set must not clobber the rest of the blob"
    assert md["parsed_sections"].present?
  end

  # ── The concurrency bound ───────────────────────────────────────────────

  test "never starts more than MAX_IN_FLIGHT_PER_ROUTE pipelines for one route" do
    assert_enqueued_jobs CP::MAX_IN_FLIGHT_PER_ROUTE, only: PIPELINE do
      CP.prefetch(@route, @steps.map(&:id))
    end
  end

  test "in-flight steps consume the budget" do
    mark(@steps[0], content_generating: true)

    assert_equal CP::MAX_IN_FLIGHT_PER_ROUTE - 1, CP.available_slots(@route)

    assert_enqueued_jobs CP::MAX_IN_FLIGHT_PER_ROUTE - 1, only: PIPELINE do
      CP.prefetch(@route, @steps.drop(1).map(&:id))
    end
  end

  test "a route at capacity enqueues nothing" do
    CP::MAX_IN_FLIGHT_PER_ROUTE.times { |i| mark(@steps[i], content_generating: true) }

    assert_equal 0, CP.available_slots(@route)
    assert_no_enqueued_jobs only: PIPELINE do
      CP.prefetch(@route, @steps.map(&:id))
    end
  end

  test "a finished in-flight step frees its slot" do
    mark(@steps[0], content_generating: true)
    assert_equal CP::MAX_IN_FLIGHT_PER_ROUTE - 1, CP.available_slots(@route)

    mark(@steps[0], content_ready: true)
    assert_equal CP::MAX_IN_FLIGHT_PER_ROUTE, CP.available_slots(@route),
      "content_ready must release the slot even though content_generating is still set"
  end

  test "one route's budget is not consumed by another route" do
    other_route = LearningRoutesEngine::LearningRoute.create!(
      learning_profile: @profile, topic: "Other", locale: "en", status: :active
    )
    other_route.route_steps.create!(title: "X", position: 0, status: :available,
      content_type: "lesson", delivery_format: "text", level: 1, bloom_level: 1,
      metadata: { "content_generating" => true })

    assert_equal CP::MAX_IN_FLIGHT_PER_ROUTE, CP.available_slots(@route)
  end

  # ── pending_step_ids ────────────────────────────────────────────────────

  test "pending excludes ready steps and assessments, nearest first" do
    mark(@steps[0], content_ready: true)
    @steps[2].update!(content_type: "assessment")

    ids = CP.pending_step_ids(@route)

    assert_not_includes ids, @steps[0].id
    assert_not_includes ids, @steps[2].id, "assessments are generated by AssessmentGenerationJob"
    assert_equal @steps[1].id, ids.first, "nearest-first"
  end

  test "pending can look only ahead of a position" do
    ids = CP.pending_step_ids(@route, after_position: 2)

    assert_equal [@steps[3].id, @steps[4].id, @steps[5].id], ids
  end

  # ── Idempotency of the whole path ───────────────────────────────────────

  test "prefetching twice in a row does not double-enqueue" do
    first = nil
    assert_enqueued_jobs CP::MAX_IN_FLIGHT_PER_ROUTE, only: PIPELINE do
      first = CP.prefetch(@route, @steps.map(&:id))
    end

    assert_no_enqueued_jobs only: PIPELINE do
      CP.prefetch(@route, @steps.map(&:id))
    end
    assert first.any?
  end
end
