module LearningRoutesEngine
  class RouteStep < ApplicationRecord
    belongs_to :learning_route
    belongs_to :route_module

    has_one :step_quiz, -> { where(assessment_type: :step_quiz) },
            class_name: "Assessments::Assessment",
            foreign_key: :route_step_id,
            dependent: :destroy

    has_many :ai_contents,
             class_name: "ContentEngine::AiContent",
             foreign_key: :route_step_id,
             dependent: :destroy

    has_many :voice_responses,
             class_name: "Assessments::VoiceResponse",
             foreign_key: :route_step_id,
             dependent: :destroy

    # Community associations
    has_many :comments, as: :commentable, class_name: "CommunityEngine::Comment", dependent: :destroy
    has_many :likes, as: :likeable, class_name: "CommunityEngine::Like", dependent: :destroy

    enum :level, { nv1: 0, nv2: 1, nv3: 2 }, prefix: true
    enum :content_type, { lesson: 0, exercise: 1, assessment: 2, review: 3 }, prefix: true
    enum :status, { locked: 0, available: 1, in_progress: 2, completed: 3 }
    enum :fsrs_state, { fsrs_new: 0, fsrs_learning: 1, fsrs_review: 2, fsrs_relearning: 3 }, prefix: true

    validates :position, presence: true,
              uniqueness: { scope: :learning_route_id },
              numericality: { greater_than_or_equal_to: 0 }
    # Raised when a step is created without a module on a route that has paid
    # modules — see `assign_preview_module`.
    class ImplicitPreviewModule < StandardError; end

    validates :title, presence: true, length: { maximum: 255 }
    validate :route_module_belongs_to_learning_route
    before_validation :assign_preview_module, on: :create

    scope :by_level, ->(level) { where(level: level) }
    scope :available_steps, -> { where(status: :available) }
    scope :completed_steps, -> { where(status: :completed) }
    scope :due_for_review, -> { where(status: :completed).where("fsrs_next_review_at <= ?", Time.current) }
    scope :reviews_only, -> { where(content_type: :review) }

    # Merge these keys into `metadata` and touch NOTHING else.
    #
    # `update!(metadata: metadata.merge(...))` rewrites the WHOLE jsonb blob from
    # whatever copy the caller happens to be holding. In a job that copy was read
    # before a multi-minute AI call, so every key written in the meantime is
    # erased on save: the `image_url` a student generated by hand,
    # `step_quiz_generated`, `audio_sections`. The generated file survives in
    # storage; its URL does not, the student regenerates, and we pay again.
    #
    # PostgreSQL's `||` merges at the top level inside the database, so keys this
    # caller does not name are read and written by nobody. Same technique as
    # ContentPrefetcher's `jsonb_set` claim, generalised to a set of keys.
    #
    # NOTE: `||` is shallow, exactly like Hash#merge. A caller mutating a NESTED
    # structure (`parsed_sections[i]["image_url"]`) must still re-read that
    # structure immediately before writing — see MediaPrefetchJob#apply_results!.
    def merge_metadata!(attributes)
      patch = attributes.deep_stringify_keys
      return self if patch.empty?

      self.class.where(id: id).update_all([
        "metadata = COALESCE(metadata, '{}'::jsonb) || ?::jsonb, updated_at = NOW()", patch.to_json
      ])

      write_attribute(:metadata, (metadata || {}).merge(patch))
      clear_attribute_changes([:metadata])
      self
    end

    # The current metadata straight from the row, for a caller about to mutate a
    # nested structure it read minutes ago.
    def fresh_metadata
      self.class.where(id: id).pick(:metadata) || {}
    end

    def complete!
      return if completed?
      update!(status: :completed, completed_at: Time.current)
    end

    def unlock!
      update!(status: :available) if locked?
    end

    def prerequisites_met?
      return true if prerequisites.blank?

      prerequisite_steps = learning_route.route_steps.where(id: prerequisites)
      prerequisite_steps.all? { |step| step.completed? }
    end

    def unlock_if_ready!
      unlock! if locked? && prerequisites_met?
    end

    def localized_title(locale = I18n.locale)
      translations.dig(locale.to_s, "title") || title
    end

    def localized_description(locale = I18n.locale)
      translations.dig(locale.to_s, "description") || description
    end

    def requires_quiz?
      content_type_lesson? || content_type_exercise?
    end

    # Blocks in this step's parsed content that gate completion and which this user has
    # not yet satisfied. Empty array means the step is free to complete.
    #
    # "Satisfied" is deliberately broader than "passed": it includes a block released
    # after BlockAttempt::RELEASE_AFTER failures, because a wrong AI answer key must not
    # trap the student. It does not include a block they simply never touched.
    def outstanding_blocks_for(user)
      # Read through SectionResolver, not the raw metadata. 14 of 21 production steps
      # had no parsed_sections, so this returned "nothing pending" for a step whose
      # page was showing an unanswered exercise, and the gate let the student past.
      sections = ContentEngine::SectionResolver.call(self)
      return [] unless sections.is_a?(Array)

      gating = sections.each_with_index.filter_map do |section, index|
        type = section.is_a?(Hash) ? (section["type"] || section[:type]).to_s : nil
        next unless type && BlockGrader.gating?(type)

        { section_index: index, block_type: type }
      end
      return [] if gating.empty?

      satisfied = BlockAttempt.where(user: user, route_step: self)
                              .satisfied
                              .pluck(:section_index)
                              .to_set

      gating.reject { |b| satisfied.include?(b[:section_index]) }
    end

    def quiz_passed_by?(user)
      step_quiz&.passed_by?(user) || false
    end

    def content_ready?
      metadata&.dig("content_ready") == true
    end

    def content_generating?
      metadata&.dig("content_generating") == true
    end

    def preview_access?
      RouteModule.where(id: route_module_id, learning_route_id: learning_route_id, access_state: :preview).exists?
    end

    def audio_delivery?
      delivery_format == "audio"
    end

    def audio_content
      ai_contents.order(created_at: :desc).first
    end

    def audio_ready?
      audio_content&.audio_ready? || false
    end

    def liked_by?(user)
      return false unless user
      if instance_variable_defined?(:@_liked_by_cached_user_id) &&
         @_liked_by_cached_user_id == user.id
        return @_liked_by_cached
      end
      likes.exists?(user_id: user.id)
    end

    private

    # Default a step with no module into the preview module.
    #
    # This is a CONVENIENCE for routes that have only one module, where there is
    # exactly one possible answer. It is NOT a safe default on a route that has
    # paid modules: preview is the filter ContentPrefetcher uses to decide what
    # to generate for free, so a billable step landing there by omission is money
    # we spend and never charge for. That is precisely how AdaptiveDifficulty's
    # reinforcement steps became free content on paid routes.
    #
    # So on a route that HAS a non-preview module, omitting `route_module` is
    # treated as a caller bug: it raises in development and test, and logs in
    # production, mirroring `strict_loading_by_default`'s posture — a student
    # mid-assessment must not get a 500 out of it, but no developer may add such
    # a caller without hearing about it. Every production creation path already
    # passes `route_module:` explicitly; only tests and single-module routes rely
    # on this default.
    def assign_preview_module
      return if route_module_id.present? || learning_route_id.blank?

      preview = RouteModule.find_by(learning_route_id: learning_route_id, access_state: :preview)
      report_implicit_preview_module! if monetised_route?
      self.route_module = preview
    end

    def monetised_route?
      RouteModule.where(learning_route_id: learning_route_id)
                 .where.not(access_state: :preview).exists?
    end

    def report_implicit_preview_module!
      message = "RouteStep created without route_module on route #{learning_route_id}, " \
                "which has paid modules; it would default into the FREE preview module. " \
                "Pass route_module: explicitly."

      raise ImplicitPreviewModule, message if Rails.env.local?

      Rails.logger.error("[RouteStep] #{message}")
    end

    def route_module_belongs_to_learning_route
      return if route_module.nil? || route_module.learning_route_id == learning_route_id

      errors.add(:route_module, "must belong to the same learning route")
    end
  end
end
