# Solid Queue recurring tasks
# https://github.com/rails/solid_queue#recurring-tasks

production:
  daily_streak_reset:
    class: DailyStreakCheckJob
    queue: low
    schedule: every day at 6am UTC

development:
  daily_streak_reset:
    class: DailyStreakCheckJob
    queue: low
    schedule: every day at 6am UTC
