require "test_helper"

module ContentEngine
  # THE CLASS: no job may write step metadata by rewriting the whole jsonb blob
  # from a copy it read before a multi-second AI call.
  #
  # MediaPrefetchJob loaded `@step` at the top, spent 1-5 minutes generating
  # images and TTS across six threads, then saved
  # `@step.metadata.merge(...)` — the blob as it looked minutes earlier. Every
  # key written in between was erased on save: the `image_url` a student had just
  # generated by hand (SectionImageJob), `step_quiz_generated`
  # (StepQuizGenerationJob), `audio_sections` (SectionAudioController). The
  # generated file survives in storage; its URL does not. The student regenerates
  # and we pay again — 4.26¢ per lost image, 3.07¢ per lost narration.
  #
  # Ten call sites had the same shape. Fixing one would have left nine.
  class StepMetadataWriteIsolationTest < ActiveSupport::TestCase
    # Jobs are not the only writers. `SectionImagesController#mark_generating!`
    # and `SectionAudioController#update_audio_status!` write the same blob from
    # a request, and `SectionAudioGenerator` writes it from a service — the
    # jobs-only glob is why they survived the first sweep while the file around
    # them was being edited for WP-33 §1.
    WRITER_GLOB = "{app,engines/*/app}/{jobs,controllers,services}/**/*.rb".freeze

    def setup
      @user = create_test_user
      profile = LearningRoutesEngine::LearningProfile.create!(user: @user, current_level: "beginner")
      @route = LearningRoutesEngine::LearningRoute.create!(
        learning_profile: profile, topic: "Metadata", locale: "en"
      )
      preview = LearningRoutesEngine::RouteModule.find_by!(
        learning_route_id: @route.id, access_state: :preview
      )
      @step = LearningRoutesEngine::RouteStep.create!(
        learning_route: @route, route_module: preview, position: 1,
        title: "Lesson", content_type: :lesson, status: :available,
        metadata: { "parsed_sections" => [{ "type" => "concept", "body" => "b" }] }
      )
    end

    # ── the primitive ───────────────────────────────────────────────────────

    test "merge_metadata! writes only the keys it names" do
      @step.merge_metadata!("audio_sections" => { "0" => { "status" => "ready" } })

      metadata = @step.reload.metadata
      assert_equal 1, metadata["parsed_sections"].size, "an untouched key must survive"
      assert_equal "ready", metadata.dig("audio_sections", "0", "status")
    end

    # ── the defect, as it actually happens: a stale in-memory copy ───────────

    test "a stale copy writing its own keys does not erase a key written meanwhile" do
      stale = LearningRoutesEngine::RouteStep.find(@step.id)

      # Someone else writes while the job holds `stale`.
      @step.merge_metadata!("step_quiz_generated" => true)

      stale.merge_metadata!("media_prefetch_completed_at" => Time.current.iso8601)

      metadata = @step.reload.metadata
      assert metadata["step_quiz_generated"],
        "the concurrent write was erased by a save built from a stale blob"
      assert metadata["media_prefetch_completed_at"].present?
    end

    # ── the job itself ──────────────────────────────────────────────────────

    test "MediaPrefetchJob's write does not erase what landed while it was working" do
      job = MediaPrefetchJob.new
      # The copy the job loaded BEFORE the minutes of generation.
      job.instance_variable_set(:@step, LearningRoutesEngine::RouteStep.find(@step.id))
      job.instance_variable_set(:@options, {})

      # A student generates an image by hand, and the quiz job finishes, while
      # the prefetch is still running.
      fresh = @step.reload.metadata["parsed_sections"]
      fresh[0]["image_url"] = "https://example.test/paid-for.png"
      @step.merge_metadata!("parsed_sections" => fresh, "step_quiz_generated" => true)

      job.send(:apply_results!, [{ "type" => "concept", "body" => "b" }], {})

      metadata = @step.reload.metadata
      assert_equal "https://example.test/paid-for.png", metadata["parsed_sections"][0]["image_url"],
        "the image the student already paid for was overwritten"
      assert metadata["step_quiz_generated"], "the quiz flag was overwritten"
      assert metadata["media_prefetch_completed_at"].present?, "the job still wrote its own keys"
    end

    # ── the controller, which mutates a NESTED structure ────────────────────
    #
    # `merge_metadata!` is shallow, exactly like `Hash#merge` — `RouteStep`
    # says so in its own comment. It keeps the top-level keys the caller does
    # not name; it cannot help a caller that rebuilds the WHOLE
    # `parsed_sections` array from a copy it read earlier and names that.
    #
    # `mark_generating!` did precisely that: it read `@step.metadata` from the
    # instance `set_step_and_authorize!` loaded at the top of the request, set
    # `image_status` on ONE entry, and wrote the whole array back. A
    # `SectionImageJob` committing another section's `image_url` in between was
    # erased — and `MediaPrefetchJob#build_media_tasks` re-queues every visual
    # whose `image_url` is blank, so the lost image is bought a second time.
    #
    # Both jobs already re-read: `SectionImageJob#write_state!` reloads,
    # `MediaPrefetchJob#apply_results!` uses `fresh_metadata`. The controller
    # was the writer left holding a stale copy.
    test "SectionImagesController#mark_generating! does not erase an image written meanwhile" do
      visuals = [
        { "type" => "visual", "image_description" => "A", "image_url" => nil },
        { "type" => "visual", "image_description" => "B", "image_url" => nil }
      ]
      @step.merge_metadata!("parsed_sections" => visuals)

      controller = ContentEngine::SectionImagesController.new
      # The copy the request loaded, BEFORE the job below commits.
      controller.instance_variable_set(:@step, LearningRoutesEngine::RouteStep.find(@step.id))

      # SectionImageJob finishes visual B while the request is in flight.
      fresh = @step.reload.metadata["parsed_sections"]
      fresh[1]["image_url"] = "https://example.test/paid-for.png"
      fresh[1]["image_status"] = "ready"
      @step.merge_metadata!("parsed_sections" => fresh)

      # The student clicks Generate on visual A.
      controller.send(:mark_generating!, 0)

      parsed = @step.reload.metadata["parsed_sections"]
      assert_equal "generating", parsed[0]["image_status"],
        "the controller must still do its own job"
      assert_equal "https://example.test/paid-for.png", parsed[1]["image_url"],
        "the image the student already paid for was erased by a whole-array write " \
        "built from the copy the request loaded before the job committed"
      assert_equal "ready", parsed[1]["image_status"]
    end

    # ── the class ───────────────────────────────────────────────────────────

    test "nothing writes step metadata with a whole-blob merge" do
      offenders = Dir[Rails.root.join(WRITER_GLOB)].select do |path|
        strip_comments(File.read(path)).match?(/update!\(\s*metadata:/)
      end

      assert_empty offenders.map { |path| Pathname.new(path).relative_path_from(Rails.root).to_s },
        "these rewrite the whole jsonb blob from a copy read before an AI call; " \
        "use RouteStep#merge_metadata! so the database keeps the keys you do not name"
    end

    test "the sweep is looking at the writers it thinks it is" do
      assert_operator Dir[Rails.root.join(WRITER_GLOB)].size, :>=, 40,
        "the glob stopped matching the tree; the class test above would pass vacuously"
    end

    # Two of the five files the widened glob matches only MENTION the whole-blob
    # write, in the comment explaining why they do not do it. Matching that
    # comment would have made the fix look like the defect.
    def strip_comments(source)
      source.lines.reject { |line| line.strip.start_with?("#") }.join
    end
  end
end
