require "test_helper"

module ContentEngine
  # THE CLASS: no job may write step metadata by rewriting the whole jsonb blob
  # from a copy it read before a multi-second AI call.
  #
  # MediaPrefetchJob loaded `@step` at the top, spent 1-5 minutes generating
  # images and TTS across six threads, then saved
  # `@step.metadata.merge(...)` — the blob as it looked minutes earlier. Every
  # key written in between was erased on save: the `image_url` a student had just
  # generated by hand (SectionImageJob), `step_quiz_generated`
  # (StepQuizGenerationJob), `audio_sections` (SectionAudioController). The
  # generated file survives in storage; its URL does not. The student regenerates
  # and we pay again — 4.26¢ per lost image, 3.07¢ per lost narration.
  #
  # Ten call sites had the same shape. Fixing one would have left nine.
  class StepMetadataWriteIsolationTest < ActiveSupport::TestCase
    JOB_GLOB = "{app/jobs,engines/*/app/jobs}/**/*.rb".freeze

    def setup
      @user = create_test_user
      profile = LearningRoutesEngine::LearningProfile.create!(user: @user, current_level: "beginner")
      @route = LearningRoutesEngine::LearningRoute.create!(
        learning_profile: profile, topic: "Metadata", locale: "en"
      )
      preview = LearningRoutesEngine::RouteModule.find_by!(
        learning_route_id: @route.id, access_state: :preview
      )
      @step = LearningRoutesEngine::RouteStep.create!(
        learning_route: @route, route_module: preview, position: 1,
        title: "Lesson", content_type: :lesson, status: :available,
        metadata: { "parsed_sections" => [{ "type" => "concept", "body" => "b" }] }
      )
    end

    # ── the primitive ───────────────────────────────────────────────────────

    test "merge_metadata! writes only the keys it names" do
      @step.merge_metadata!("audio_sections" => { "0" => { "status" => "ready" } })

      metadata = @step.reload.metadata
      assert_equal 1, metadata["parsed_sections"].size, "an untouched key must survive"
      assert_equal "ready", metadata.dig("audio_sections", "0", "status")
    end

    # ── the defect, as it actually happens: a stale in-memory copy ───────────

    test "a stale copy writing its own keys does not erase a key written meanwhile" do
      stale = LearningRoutesEngine::RouteStep.find(@step.id)

      # Someone else writes while the job holds `stale`.
      @step.merge_metadata!("step_quiz_generated" => true)

      stale.merge_metadata!("media_prefetch_completed_at" => Time.current.iso8601)

      metadata = @step.reload.metadata
      assert metadata["step_quiz_generated"],
        "the concurrent write was erased by a save built from a stale blob"
      assert metadata["media_prefetch_completed_at"].present?
    end

    # ── the job itself ──────────────────────────────────────────────────────

    test "MediaPrefetchJob's write does not erase what landed while it was working" do
      job = MediaPrefetchJob.new
      # The copy the job loaded BEFORE the minutes of generation.
      job.instance_variable_set(:@step, LearningRoutesEngine::RouteStep.find(@step.id))
      job.instance_variable_set(:@options, {})

      # A student generates an image by hand, and the quiz job finishes, while
      # the prefetch is still running.
      fresh = @step.reload.metadata["parsed_sections"]
      fresh[0]["image_url"] = "https://example.test/paid-for.png"
      @step.merge_metadata!("parsed_sections" => fresh, "step_quiz_generated" => true)

      job.send(:apply_results!, [{ "type" => "concept", "body" => "b" }], {})

      metadata = @step.reload.metadata
      assert_equal "https://example.test/paid-for.png", metadata["parsed_sections"][0]["image_url"],
        "the image the student already paid for was overwritten"
      assert metadata["step_quiz_generated"], "the quiz flag was overwritten"
      assert metadata["media_prefetch_completed_at"].present?, "the job still wrote its own keys"
    end

    # ── the class ───────────────────────────────────────────────────────────

    test "no job writes step metadata with a whole-blob merge" do
      offenders = Dir[Rails.root.join(JOB_GLOB)].select do |path|
        File.read(path).match?(/update!\(\s*metadata:/)
      end

      assert_empty offenders.map { |path| Pathname.new(path).relative_path_from(Rails.root).to_s },
        "these rewrite the whole jsonb blob from a copy read before an AI call; " \
        "use RouteStep#merge_metadata! so the database keeps the keys you do not name"
    end

    test "the sweep is looking at the jobs it thinks it is" do
      assert_operator Dir[Rails.root.join(JOB_GLOB)].size, :>=, 15,
        "the glob stopped matching the job tree; the class test above would pass vacuously"
    end
  end
end
